# Generated by Django 3.2.5 on 2021-07-28 05:57

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_donor'),
    ]

    operations = [
        migrations.AddField(
            model_name='donor',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(default='+8801954492600', max_length=128, region=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='donor',
            name='share_phone',
            field=models.BooleanField(default=True),
        ),
    ]
