# Generated by Django 3.2.6 on 2021-09-03 20:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_requestphoneoremail'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_1', models.CharField(max_length=60)),
                ('address_2', models.CharField(blank=True, max_length=60, null=True)),
                ('postal', models.IntegerField(max_length=6)),
                ('city', models.CharField(max_length=40)),
                ('district', models.CharField(max_length=40)),
                ('division', models.CharField(max_length=40)),
                ('country', models.CharField(max_length=40)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
