# Generated by Django 3.2.6 on 2021-09-04 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_address_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='address_1',
            new_name='address_one',
        ),
        migrations.RenameField(
            model_name='address',
            old_name='address_2',
            new_name='address_two',
        ),
    ]
