# Generated by Django 3.2.6 on 2021-09-04 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20210905_0321'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='address_one',
            new_name='address_line_one',
        ),
        migrations.RenameField(
            model_name='address',
            old_name='address_two',
            new_name='address_line_two',
        ),
    ]
