# Generated by Django 3.2.6 on 2021-09-04 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20210905_0322'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='address_line_one',
            new_name='address_line_1',
        ),
        migrations.RenameField(
            model_name='address',
            old_name='address_line_two',
            new_name='address_line_2',
        ),
    ]
