# Generated by Django 3.2.6 on 2021-09-04 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20210905_0323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donor',
            name='blood_group',
            field=models.CharField(choices=[('a+', 'a+'), ('b+', 'b+'), ('a-', 'a-'), ('b-', 'b-'), ('ab+', 'ab+'), ('ab-', 'ab-'), ('o+', 'o+'), ('o-', 'o-')], max_length=3),
        ),
    ]
