# Generated by Django 3.2.6 on 2021-10-25 17:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_alter_donor_blood_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='BloodGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blood_group', models.CharField(choices=[('a+', 'a+'), ('b+', 'b+'), ('a-', 'a-'), ('b-', 'b-'), ('ab+', 'ab+'), ('ab-', 'ab-'), ('o+', 'o+'), ('o-', 'o-')], max_length=3)),
            ],
        ),
        migrations.AlterField(
            model_name='donor',
            name='blood_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.bloodgroup'),
        ),
    ]
