# Generated by Django 3.2.6 on 2021-11-23 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_auto_20211025_2304'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bloodgroup',
            name='blood_group',
        ),
        migrations.AddField(
            model_name='bloodgroup',
            name='factor',
            field=models.CharField(choices=[('p', '+'), ('n', '-')], default=1, max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bloodgroup',
            name='type',
            field=models.CharField(choices=[('a', 'a'), ('b', 'b'), ('ab', 'ab'), ('o', 'o')], default=1, max_length=2),
            preserve_default=False,
        ),
    ]
