# Generated by Django 3.2.6 on 2021-11-23 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_auto_20211124_0404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donor',
            name='share_phone',
            field=models.BooleanField(default=False),
        ),
    ]
