# Generated by Django 3.2.6 on 2021-11-24 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_rename_postal_address_are_zip'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='are_zip',
            new_name='postcode',
        ),
        migrations.RenameField(
            model_name='address',
            old_name='address_line_1',
            new_name='suburb',
        ),
        migrations.RemoveField(
            model_name='address',
            name='address_line_2',
        ),
        migrations.AlterUniqueTogether(
            name='bloodgroup',
            unique_together={('type', 'factor')},
        ),
    ]
