# Generated by Django 3.2.6 on 2021-11-24 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_alter_bloodgroup_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='donor',
            name='is_donor',
            field=models.BooleanField(default=True),
        ),
    ]
