# Generated by Django 3.2.6 on 2021-11-24 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_donor_is_donor'),
    ]

    operations = [
        migrations.AddField(
            model_name='donor',
            name='last_donation',
            field=models.DateField(blank=True, null=True),
        ),
    ]
