# Generated by Django 3.2.6 on 2021-11-24 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_donor_last_donation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='suburb',
            new_name='address',
        ),
    ]
