# Generated by Django 3.2.6 on 2021-11-24 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_rename_suburb_address_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='division',
        ),
    ]
