# Generated by Django 4.0 on 2021-12-29 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_auto_20211128_2230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloodgroup',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='bloodgroup',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='donor',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='donor',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
