# Generated by Django 3.1.3 on 2021-06-25 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_bag_required', models.IntegerField()),
                ('no_bag_managed', models.IntegerField()),
                ('is_emergency', models.BooleanField(default=False)),
            ],
        ),
    ]
