# Generated by Django 4.0 on 2022-01-04 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('donation', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='phonesharerequest',
            name='receiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receiver', to='users.donor'),
        ),
        migrations.AddField(
            model_name='phonesharerequest',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sender', to='users.user'),
        ),
        migrations.AddField(
            model_name='bloodrequestresponse',
            name='blood_request',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='donation.bloodrequest'),
        ),
        migrations.AddField(
            model_name='bloodrequestresponse',
            name='respondent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='donor_profile', to='users.donor'),
        ),
        migrations.AddField(
            model_name='bloodrequest',
            name='blood_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.bloodgroup'),
        ),
        migrations.AddField(
            model_name='bloodrequest',
            name='hospital',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='donation.hospital'),
        ),
        migrations.AddField(
            model_name='bloodrequest',
            name='receiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_receiver', to='users.user'),
        ),
    ]
