# Generated by Django 3.2.6 on 2021-11-24 16:21

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0003_auto_20210705_2032'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('address', models.CharField(max_length=300)),
                ('city', models.CharField(max_length=50)),
                ('area_zip', models.IntegerField()),
                ('country', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='bloodrequest',
            name='phone_emergency',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None),
        ),
        migrations.AddField(
            model_name='bloodrequest',
            name='hospital',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='donation.hospital'),
            preserve_default=False,
        ),
    ]
