# Generated by Django 3.2.6 on 2021-11-27 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0004_auto_20211124_2221'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bloodrequest',
            old_name='phone_emergency',
            new_name='phone_additional',
        ),
        migrations.AddField(
            model_name='bloodrequest',
            name='needs_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bloodrequest',
            name='no_bag_managed',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
