# Generated by Django 3.2.6 on 2021-11-28 03:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_remove_address_division'),
        ('donation', '0005_auto_20211127_2214'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloodrequest',
            name='blood_group',
            field=models.ForeignKey(default=18, on_delete=django.db.models.deletion.PROTECT, to='users.bloodgroup'),
            preserve_default=False,
        ),
    ]
