# Generated by Django 3.2.6 on 2021-12-02 21:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_auto_20211128_2230'),
        ('donation', '0008_auto_20211128_2230'),
    ]

    operations = [
        migrations.CreateModel(
            name='BloodRequestResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fullfilled', models.BooleanField(default=False)),
                ('blood_request', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='donation.bloodrequest')),
                ('respondent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.donor')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
