# Generated by Django 3.2.6 on 2021-12-03 11:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_auto_20211128_2230'),
        ('donation', '0011_alter_bloodrequestresponse_respondent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloodrequestresponse',
            name='respondent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='respondent', to='users.donor'),
        ),
    ]
