# Generated by Django 3.2.6 on 2021-12-05 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0014_alter_bloodrequestresponse_respondent'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='bloodrequestresponse',
            unique_together=set(),
        ),
    ]
