# Generated by Django 3.2.6 on 2021-12-28 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0015_alter_bloodrequestresponse_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloodrequestresponse',
            name='blood_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='blood_request', to='donation.bloodrequest'),
        ),
    ]
