# Generated by Django 4.0 on 2021-12-29 22:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0019_alter_bloodrequestresponse_blood_request'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloodrequestresponse',
            name='blood_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='request', to='donation.bloodrequest'),
        ),
    ]
