# Generated by Django 4.0 on 2021-12-29 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0021_alter_bloodrequestresponse_blood_request'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bloodrequestresponse',
            old_name='blood_request',
            new_name='request',
        ),
    ]
