# Generated by Django 4.0 on 2021-12-29 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0022_rename_blood_request_bloodrequestresponse_request'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bloodrequestresponse',
            old_name='request',
            new_name='blood_request',
        ),
    ]
