# Generated by Django 4.0 on 2021-12-30 20:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0023_rename_request_bloodrequestresponse_blood_request'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloodrequestresponse',
            name='blood_request',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='donation.bloodrequest'),
        ),
    ]
